// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLGT_API.Data;

namespace QLGT_API.Migrations
{
    [DbContext(typeof(QLGTDBContext))]
    partial class QLGTDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("QLGT_API.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("QLGT_API.Models.BangLaiModel", b =>
                {
                    b.Property<string>("MA_BANG_LAI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HOAT_DONG")
                        .HasColumnType("int");

                    b.Property<string>("MA_KHACH_HANG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MA_LOAI_BANG_LAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAY_CAP_NCK")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAY_CAP_NHAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAY_TAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOI_CAP_NCK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("THOI_HAN_SU_DUNG")
                        .HasColumnType("int");

                    b.HasKey("MA_BANG_LAI");

                    b.ToTable("BANG_LAI");
                });

            modelBuilder.Entity("QLGT_API.Models.KhachHangModel", b =>
                {
                    b.Property<string>("MA_KHACH_HANG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIA_CHI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GIOI_TINH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HOAT_DONG")
                        .HasColumnType("int");

                    b.Property<DateTime>("NGAY_CAP_NHAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAY_TAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("QUOC_TICH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEN_KHACH_HANG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TUOI")
                        .HasColumnType("int");

                    b.HasKey("MA_KHACH_HANG");

                    b.ToTable("KHACH_HANG");
                });

            modelBuilder.Entity("QLGT_API.Models.LoaiBangLaiModel", b =>
                {
                    b.Property<string>("MA_LOAI_BANG_LAI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MO_TA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEN_LOAI_BANG_LAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MA_LOAI_BANG_LAI");

                    b.ToTable("LOAI_BANG_LAI");
                });
#pragma warning restore 612, 618
        }
    }
}
